my_string = input("Напишите что-нибудь: ")
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print(f'Первый символ строки: "{my_string[0]}"')
print(f'Последний символ строки: "{my_string[0]}"')
